---
title: "ETC5543 project"
author: "Qin xu"
date: "2022-09-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
  message = FALSE,
  warning = FALSE,
  error = FALSE, 
  collapse = TRUE,
  comment = "#",
  fig.height = 4,
  fig.width = 8,
  out.width = "100%",
  fig.align = "center",
  fig.retina = 4,
  cache = FALSE)
  
```

```{r libraries}
library(tidyverse)
library(ggplot2)
library(sugarbag)
library(cubble)
library(here)
library(sf)
library(lubridate)
library(giscoR)
```


```{r dataset}
#map data
lhd_metro <- read_sf(here::here("nsw-localhealthdistricts.kml"), layer = "Metropolitan local health districts")
lhd_rural <- read_sf(here::here("nsw-localhealthdistricts.kml"), layer = "Rural and regional NSW local health districts")
lhd_map <- rbind(lhd_metro,lhd_rural)

# confirm case data 
confirmed_case<- read_csv("confirmed_cases_table1_location_agg.csv")
confirmed_case<- confirmed_case %>% 
  select("notification_date",
         "lhd_2010_code",
         "lhd_2010_name",
         "confirmed_cases_count") 

```


```{r confirm_cases}
# Number of confirmed cases from 2020-01-25 to 2022-08-30 - Base on local health district
total_confirm_cases <- confirmed_case %>% 
  group_by(lhd_2010_name) %>% 
 summarise(Total_confirm_case = sum(confirmed_cases_count)) %>% 
  rename( "Name" = lhd_2010_name)
total_confirm_cases

# Number of monthly confirmed cases from 2020-01-23 to 2022-08-30 - Base on local health district. 

monthly_confirmed_cases<- confirmed_case %>% 
  mutate ( month_year =  format(confirmed_case$notification_date ,"%Y-%m")) %>%  group_by(lhd_2010_name,month_year) %>% 
 summarise(Total_confirm_case = sum(confirmed_cases_count)) %>% 
  rename( "Name" = lhd_2010_name)
monthly_confirmed_cases

# Number of weekly confirmed cases  from 2020-01-23 to 2022-08-30 - Base on local health district. 
weekly_confirmed_cases<- confirmed_case %>% 
  mutate (week = week(ymd(notification_date))) %>% 
  rename( "Name" = lhd_2010_name)

weekly_confirmed_cases <-  weekly_confirmed_cases %>%  
  mutate ( Year =  format(confirmed_case$notification_date ,"%Y")) %>% 
  group_by(Name,Year,week )  %>% 
 summarise(Total_confirm_case = sum(confirmed_cases_count)) 
weekly_confirmed_cases
```

```{r Choropleth_map}
lhd_metro
lhd_rural
# combining aggregated data with map
lhd_total <-  merge( x = lhd_map, y = total_confirm_cases , by = "Name" )
lhd_month <-  merge( x = lhd_map, y = monthly_confirmed_cases , by = "Name")

# create choropleth plot with total and monthly data 
choropleth_plot_total <- lhd_total %>%  
  ggplot() + 
  geom_sf(aes(fill = Total_confirm_case)) + 
  geom_sf_label(aes(label = Name))
  labs( title = " Choropleth map of COVID Confirm Cases accross NSW Local Health Distirct ") +
  theme_bw() 
  
choropleth_plot_total

head(lhd_map)
plot(lhd_map)
```

